### ISSUE TITLE
can not run in tensorflow 0.12.1

### ISSUE THREAD

**Issue by huangpeng1126** [devsisters/pointer-network-tensorflow#7]
When I run the main.py, getting the following errors:
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    from trainer import Trainer
  File "/Users/peng.huangp/github/pointer-network-tensorflow/trainer.py", line 7, in <module>
    from model import Model
  File "/Users/peng.huangp/github/pointer-network-tensorflow/model.py", line 4, in <module>
    from layers import *
  File "/Users/peng.huangp/github/pointer-network-tensorflow/layers.py", line 22, in <module>
    dynamic_rnn_decoder = tf.contrib.seq2seq.dynamic_rnn_decoder
AttributeError: 'module' object has no attribute 'dynamic_rnn_decoder'

I check 0.1.2.1 API of tensorflow, and can not find the definition for 'dynamic_rnn_decoder', and it is in the 0.1.0 API

**Comment by NYUXiaowen-Wang** [comment]
hi, I met the same problem with you. But the 0.1.0 api is not available now, is there something I can do to fix it? Thank you very much!

**Comment by unnir** [comment]
same story
